# Generated by Django 5.1.2 on 2024-10-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('token', models.TextField(unique=True)),
            ],
        ),
    ]
