# Generated by Django 5.1.2 on 2024-10-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationApp', '0002_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
