# Generated by Django 5.1.2 on 2024-10-16 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationApp', '0003_remove_session_id_alter_session_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('rating', models.IntegerField()),
                ('public', models.BooleanField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinationApp.user')),
            ],
        ),
    ]
