# Generated by Django 5.1.2 on 2024-10-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationApp', '0004_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='review',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
