[tool.poetry]
name = "assn3"
version = "0.1.0"
description = ""
authors = ["Ben Wheeler"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^5.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
